### ISSUE TITLE
Reference to something similar

### ISSUE THREAD

**Issue by ugurdogrusoz** [yitepeli/CS319Project_Group2D_LOST#1]
Can you guys perhaps provide a reference to some similar software? If not, you might want to explain it a bit more in detail.

**Comment by gunduzhuseyn** [comment]
I added a few similar games to 'readme' file, which helped us in deciding on the LOST game. LOST will be a more advanced version of the 'Survival Island' with a simple GUI and more objects, areas and interactions.

**Comment by ugurdogrusoz** [comment]
Thanks @gunduzhuseyn
