### ISSUE TITLE
Map Image for Lost

### ISSUE THREAD

**Issue by sonmezonur** [yitepeli/CS319Project_Group2D_LOST#6]
![map_last](https://cloud.githubusercontent.com/assets/12400946/23260276/a9da4ba6-f9d9-11e6-94be-0d7f280e0aca.jpg)

**Comment by yitepeli** [comment]
![a9da4ba6-f9d9-11e6-94be-0d7f280e0aca](https://cloud.githubusercontent.com/assets/16493194/23261636/e8c014ee-f9df-11e6-8a13-4d1099100694.jpg)

**Comment by yitepeli** [comment]
![yeni](https://cloud.githubusercontent.com/assets/16493194/23261947/73c95734-f9e1-11e6-8601-33b4f75651d8.jpg)
